version: '3.9'

services:
  db:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: 'redis:5-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  db:
  redis: